### ISSUE TITLE
Not work data and receive call

### ISSUE THREAD

**Issue by opnay** [exynos5410/android_device_samsung_jalteskt#1]
I found ss222 modem patches for lte, can't work this?

https://github.com/cm-3470/android_device_samsung_smdk3470-common/blob/cm-14.1/patch/hardware_samsung_ril/0001-add-support-for-ss222.patch

p.s// I want to build with this patch, be out of condition.... :(

**Comment by Alberto96** [comment]
Doesn't work, already tested.
